%\VignetteEngine{knitr}
%\VignetteIndexEntry{An overview of the debate package}
\documentclass{article}
\title{An overview of the debate package}
\author{Emmanuel Rousseaux and Marion Deville}
\date{\today}

\begin{document}

\maketitle

\vspace*{2cm}

\tableofcontents

\newpage

<<echo=FALSE, message=FALSE>>=
library(debate)
@


\section{Introduction}

The \verb|debate| package offers methods for measuring content and relational in (political) debates.

\end{document}